clear and save/print buttons
shiraliyeva/Group101 pull request #15
Opened 2023-11-30 21:42 UTC by aliezz19

Implemented the clear and save/print buttons to function.

2023-11-30 22:16 UTC, shiraliyeva approved these changes
Everything looks good, but there are some CA violations! 
Have a look at where you are calling the DAO.
Also the Controllers in TextAreaView should be called in a different way, but we can fix that easily after we merge with the other features.

2023-11-30 23:38 UTC, nothing128 requested changes
Nice work! Most of the code is fine, but a bit of it violates CA.

- [ ] In SavePresenter, move the DataAccessObject call to main
- [ ] In textAreaView, ClearPresenter and ClearInteractor should not directly Interact with View
- [ ] The same issue exists with SavePresenter and ClearInteractor

2023-11-30 23:38 UTC, nothing128 commented on src/interface_adapter/save_text/SavePresenter.java
> +        SaveDataAccessObject.saveToPDF(outputData.getOutputText());
Data Access Objects should only be called in Main

2023-11-30 23:38 UTC, nothing128 commented on src/view/TextAreaView.java
> +            final ClearOutputBoundary clearOutputBoundary = new ClearPresenter(clearViewModel, textArea);
ClearPresenter and ClearInteractor cannot be directly created from TextAreaView as it violates CA

2023-11-30 23:38 UTC, nothing128 commented on src/view/TextAreaView.java
> +            final SaveInputBoundary saveUseCaseInteractor = new SaveInteractor(saveOutputBoundary);
SavePresenter and SaveInteractor cannot be directly created in View as it violates CA.

2023-12-01 22:12 UTC, shiraliyeva approved these changes
Great progress! Looks good, just one minor change i would suggest. Since we are not using ClearViewModel anymore, I think you may omit that from ClearPresenter.

2023-12-02 02:44 UTC, nothing128 approved these changes
Looks good!

2023-12-02 02:45 UTC, merged